### ISSUE TITLE
sc.exe - Create vs Config

### ISSUE THREAD

**Issue by iKarthik** [SharpeRAD/Cake.Services#1]
I was looking at ServiceManager.cs and noticed this

`if (this.ServiceExists(settings.ServiceName, computer))
                {
                    //Create
                    script = "& \"sc.exe\" create";
                }
                else
                {
                    //Config
                    script = "& \"sc.exe\" config";
                }`

Which to me looks like we are calling "sc.exe create" if service specified exists and "sc.exe config" if the service doesn't exists. Shouldn't this be the other way around?

Thanks
Kay

**Comment by SharpeRAD** [comment]
Good catch :+1: its been resolved in v0.2.2
