### ISSUE TITLE
The escape character for the binPath is incorrect, causing the install to fail as it is executed via powershell

### ISSUE THREAD

**Issue by AdrianLogan** [SharpeRAD/Cake.Services#11]
If Arguments are supplied in the settings the binPath is setup with these [arguments ](https://github.com/SharpeRAD/Cake.Services/blob/431e8e0cc4ffdcb67435d5f4e96a04306aff2d10/src/Services/Manager/ServiceManager.cs#L941) appended. A backslash is used to escape the quotes when adding the ExecutablePath, which is causing the command to fail during  powershell execution.

If we trap the command and execute it from a dos prompt the command works as expected
![image](https://user-images.githubusercontent.com/723206/28320313-8a074946-6bd0-11e7-9686-d98350d0d9bc.png)

Note the backslash in the command above i.e binPath= "\\"C:/Projects/RainFin/RainFinBankingInterface/H2H/Source/Router/RainFin.H2H.Router.Processing.Service/bin/Release/NServiceBus.Host.exe\\"  -service"
 
But when run from powershell  the command fails (sc just displays the help screen but the cake build does not fail). 
![image](https://user-images.githubusercontent.com/723206/28320568-35765ec0-6bd1-11e7-94ae-16d33263ce05.png)

The reason is that the you need to used the a [backtick](https://stackoverflow.com/a/18313593) to escape characters in powershell or use the [@""](https://stackoverflow.com/a/18120114)

**Comment by SharpeRAD** [comment]
Fixed in v0.2.9 👍
