### ISSUE TITLE
Operations on Service with name containing '$' character fail

### ISSUE THREAD

**Issue by wojciechrak** [SharpeRAD/Cake.Services#16]
I have a service, whose name contains dollar sign `$`.
That's because it's Topshelf service with named instance, so convention there is `ServiceName$Instance`.

Therefore operating on service using e.g. `StopService()` is impossible, because it's using quoted arguments, which in powershell are evaluated during execution.

So `sc.exe stop MyService$InstanceA` in powershell would be evaluated to `sc.exe stop MyService`;
Evaluation can be prevented using single quotes, or StringLiteralArgument.

**Comment by SharpeRAD** [comment]
Sorry but this addin uses _System.ServiceProcess.ServiceController_ to start / stop services, not Powershell...

**Comment by wojciechrak** [comment]
I am sure I've seen some code with powershell and `sc.exe` here... I will check again.

**Comment by wojciechrak** [comment]
Ok, my bad. It's not `Start/Stop` but `Install/Uninstall` methods. https://github.com/SharpeRAD/Cake.Services/blob/2bd916474a72e7e0ddde33624f4c20dc4ea613a2/src/Cake.Services/Manager/ServiceManager.cs#L883

Installing a service with `ServiceName = "MyService$InstanceA"` actually installs it with name `MyService`.
