### ISSUE TITLE
The type name 'ServiceController' could not be found in the namespace 'System.ServiceProcess'.

### ISSUE THREAD

**Issue by GeekyGentleman** [SharpeRAD/Cake.Services#20]
I got an error message when using Cake.Services
The type name 'ServiceController' could not be found in the namespace 'System.ServiceProcess'. This type has been forwarded to assembly 'System.ServiceProcess, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' Consider adding a reference to that assembly. [release.cake]
This is how I add to the header file.
#addin "nuget:?package=Cake.Services&version=0.3.2"

**Comment by SharpeRAD** [comment]
I would assume that your referencing ServiceController in your script without including a reference to System.ServiceProcess.
