### ISSUE TITLE
Support .NET Standard 2.0

### ISSUE THREAD

**Issue by richardgavel** [SharpeRAD/Cake.Services#30]
Could you create a .NET Standard 2.0 tool so this addin can be used by the Cake global tools, which uses .NET Core?

There is a NuGet package that can be references in lieu of the reference assembly System.ServiceProcess. https://www.nuget.org/packages/System.ServiceProcess.ServiceController/

**Comment by SharpeRAD** [comment]
.net core support was added in `v.1.0.0`
